### ISSUE TITLE
zipmap crash

### ISSUE THREAD

**Issue by chrisflesher** [saidsef/terraform-gcp-github-oidc#26]
### Steps to Reproduce:
I used the default values for most things but `terraform plan` fails.

### Actual Result:
```
Error: Error in function call
│ 
│   on .terraform/modules/github_oidc/main.tf line 31, in resource "google_service_account_iam_member" "sa":
│   31:   for_each = zipmap([for repo in var.repositories : repo.org_name], var.repositories)
│     ├────────────────
│     │ while calling zipmap(keys, values)
│     │ var.repositories is list of object with 1 element
```

**Comment by saidsef** [comment]
@chrisflesher you will have to add `repositories` variable values , I've updated the docs and examples: https://github.com/saidsef/terraform-gcp-github-oidc#deployment--usage

Initially I made the service account optional - and by extension the repositories, then it became apparent without the service account the credentials are not usable, as you will need provide and service account address/path.

**Comment by chrisflesher** [comment]
Thanks, specifying the repo worked!
